--- 
- hosts: all 
  become: yes 
  tasks: 
  - name: install java on ubuntu 
    apt: 
      name: default-jdk
      update_cache: yes
      state: absent
      purge: yes
  - name: install apache2 
    apt: 
      name: apache2 
      state: absent 
  - name: install tomcat8 on ubuntu 
    apt: 
      name: tomcat8 
      state: absent 
  - name: install git on ubuntu 
    apt: 
      name: git-all
      state: absent
  - name: install tree on ubuntu 
    apt: 
      name: tree
      state: absent 
  
