- hosts: all 
  become: yes
  tasks: 
  - name: install apache2 
    apt: 
      name: apache2
      update_cache: yes
      state: absent  
  - name: create directory  
    file: 
     path: /home/ansible/new
     state: absent   