---
- hosts: all 
  become: yes 
  vars: 
    package_ubuntu_webserver: nginx 
    package_centos_webserver: httpd 
  tasks: 
  - name: install LAMP on ubuntu  
    block: 
     - name: install apache2 
       apt: 
          name: "{{ package_ubuntu_webserver }}"
          update_cache: yes   
          state: present 
     - name: install multiple packages using with items 
       apt: 
          name: "{{ item }}"
          state: present 
       with_items: 
          - php
          - libapache2-mod-php
          - php-mysql  
     - name: restart apache2 service
       service: 
          name: "{{ package_ubuntu_webserver }}"
          state: restarted 
    when: anisble_os_family == "Debian" 
  - name: install LAMP on centos 
    block: 
      - name: install lamp on centos 
        yum: 
           name: "{{ package_centos_webserver }}"
           state: present  
      - name: start and enable service 
        systemd:
          name: "{{ package_centos_webserver }}"
          state: started
          enabled: yes  
      - name: install php and php-mysql 
        yum: 
          name: "{{ item }}"
          state: present 
        loop: 
        - php
        - php-mysql
      - name: restart httpd service
        service: 
          name: "{{ package_centos_webserver }}"
          state: restarted 
      - name: copy file to nodes 
        copy: 
          src: info.php
          dest: /var/www/html/info.php 
    when: ansible_od_family == "RedHat" 
      