- name: install apache2 on ubuntu 
  apt: 
    name: "{{ package_web }}"
    update_cache: yes   
    state: present 
  when: ansible_os_family == "Debian"
- name: install multiple packages using with items 
  apt: 
    name: "{{ item }}"
    state: present 
  loop: 
    - php
    - libapache2-mod-php
    - php-mysql  
  notify: apache2 restart
  when: ansible_os_family == "Debian"  
- name: copy file to nodes 
  copy: 
      src: info.php
      dest: "{{ dest_path }}"