- hosts: all
  become: yes
  tasks: 
  - name: install apache2 on ubuntu 
    apt: 
      name: apache2
      update_cache: yes
      state: present 
    when: ansible_os_family == "Debian"
  - name: install httpd on centos 
    yum: 
     name: httpd 
     state: present 
    when: ansible_os_family == "RedHat"
  - name: start httpd service 
    service: 
      name: httpd
      state: started
    when: ansible_os_family == "RedHat" 