apiVersion:  v1
Kind: Pod
metadata:
 name: appserver 
 labels: 
   pod: app 
   server: tomcat  
 namespace: dev  
spec: 
  containers: 
   - image: nginx 
     name: webserver 
     ports: 
       - containerPort: 80 
         protocol: TCP  

--- 

   
  



