apiVersion: apps/v1
Kind: Deployment
metadata: 
  name: webserver
spec: 
  replicas: 5
  selector:
   matchLabels: 
      web: server
  template: 
     metadata: 
        name: webpod
        lables:
          web: server
     spec: 
      containers: 
       - image: nginx
         name: webserver
         ports: 
         - containerPort: 80 