- hosts: all 
  becomes: true 
  tasks: 
  - name: update packages and install apache2
    apt:
      name: apache2 
      state: present
      update_cache: yes
  - name: install packgaes php libapache2-mod-php php-mysql
    apt:
        name: "{{ item }}"
        state: present
    loop:
       - php
       - libapache2-mod-php
       - php-mysql
    notify: restart apache2 on ubuntu  
  - name: copy file from ACS to all nodes 
    copy: 
      src: /home/ansible/info.php
      dest: /var/www/html/info.php 
    notify: restart apache2 on ubuntu 
  handlers: 
  - name: restart apache2 on ubuntu 
    service: 
        name: apache2
        state: restarted 